FROM postgres:15.1-alpine

RUN apk update && apk add make clang gcc libc-dev llvm git

WORKDIR /tmp
RUN git clone https://github.com/theory/pg-semver.git
WORKDIR /tmp/pg-semver
RUN make
RUN make install
# RUN make installcheck PGUSER=postgres

# Fetch latest version of message-db
WORKDIR /opt
RUN git clone https://github.com/tqwewe/message-db ##################
# Create message-db init script
RUN echo "#!/bin/bash" > /docker-entrypoint-initdb.d/1_init-message-db.sh
RUN echo "cd /opt/message-db/database/; CREATE_DATABASE=off DATABASE_NAME=postgres ./install.sh" >> /docker-entrypoint-initdb.d/1_init-message-db.sh

COPY eventstore.sql /docker-entrypoint-initdb.d/2_eventstore.sql

EXPOSE 5432
CMD ["postgres"]
